.github/workflows/python-lint.yml
backend/.flake8
backend/.gitignore
backend/README.md
backend/pyproject.toml
backend/requirements.txt
backend/src/main.py

- Setup linting via [flake8](https://github.com/pycqa/flake8) and formatting with [black](https://github.com/psf/black)
- Add initial backend structure under `backend/`
- Add CI/CD for linting (Black + Flake8)

chore(backend): add linting workflow and initial project setup

---

README.md

Hey all,
With this PR I've structured the README file.  It is mainly a placeholder has the project hasn't fully kickstarted yet. Folder structure may be discussed together :)

feat: initial readme

---

GUIDELINES.md
README.md

Initial draft; open for review/comments.

Docs: create coding guidelines md file

---

README.md
backend/app/main.py
backend/requirements.txt
frontend/app/root.tsx
frontend/package-lock.json
frontend/package.json

Closes #38.
- Add sentry-react monitoring config for error and performance tracking
- Add sentry-browser integration to allow bug-reports
- Add session replay config
- Integrate Sentry SDK for backend error monitoring with environment and PII settings
See also [csee.sentry.io](https://csee.sentry.io/).

feat: add sentry integration

---

backend/.gitignore
backend/app/core/logger.py
backend/app/main.py
backend/docker-compose.yml

- Created app/core/logger.py to set up a reusable logger.
- Integrated the logger in main.py to log app startup.
- Tested it by running the FastAPI app
- Log messages show time, log level, and module name.
- Supports INFO, DEBUG, and ERROR levels for development and production use.
- Logger messages confirm application startup in the terminal.

feat(logger): integrate structured logger and initialize in main

---

frontend/.env.example
frontend/.gitignore
frontend/app/root.tsx

Frontend:
- root.tsx: simply added hotjar script tag to track user actions

feat: added User Analytics using Hotjar

---

.github/workflows/backend-premerge.yml

Backend team complained it was slowing them down.

Reduce test coverage from 75 to 50

---

frontend/app/custom-components/header.tsx
frontend/app/pages/welcome/welcome.tsx

fix: redirect on sign-in & view admin settings

---

backend/app/core/db.py
backend/app/main.py
scripts/docker-compose.dev.yml

fix:
- database population on fastapi startup

fix: database population

---

backend/requirements.txt

fix: update dependencies in requirements.txt

---

backend/app/repositories/user_repository.py
frontend/app/custom-components/header.tsx
frontend/types/model.ts

Note: the backend changes have bee n discussed in the previous backend PR, and thus are included here as follow-up
see #174

feat: show user organization

---

frontend/app/pages/error/error.tsx

chore: redirect organization users

---

backend/app/services/article_vector_service.py

See https://github.com/jst-seminar-rostlab-tum/eutop-mediamind/commit/e6fe65db672f9b9b6df654cda1ac70edba9dd637

Remove hardcoded collection_name

---

frontend/app/custom-components/profile/edit/edit-profile.tsx

chore: remove log

---

frontend/app/custom-components/profile/edit/edit-profile.tsx

fix: break long profile names

---

frontend/app/routes.ts

fix: router issue

---

backend/app/services/email_service.py

"Good morning, Mr./Ms. None"
The problem was that the email is not registered in the users table. Just added a conditional

Fix None in email

---

backend/app/schemas/chatbot_schemas.py
scripts/trigger_chat.py

Update lambda response body and chatbot controller

---

backend/app/repositories/match_repository.py
backend/app/services/article_matching_service.py

feat: enhance matching logic to skip existing matches and log results

---

frontend/app/app.css
frontend/app/custom-components/article/article-body.tsx
frontend/package-lock.json
frontend/package.json

Add markdown support article page

---

apps/frontend/app/custom-components/article/article-sidebar.tsx
apps/frontend/public/locales/de/translations.json
apps/frontend/public/locales/en/translations.json

Only show 5 keywords article page meta data info

---

apps/frontend/app/custom-components/breadcrumb-skeleton.tsx
apps/frontend/app/custom-components/reports/report-card-skeleton.tsx
apps/frontend/app/pages/reports/reports.tsx
apps/frontend/public/locales/de/translations.json
apps/frontend/public/locales/en/translations.json

Add reports skeleton

---

apps/frontend/app/custom-components/article/article-page-skeleton.tsx
apps/frontend/app/routes/article.tsx

Add skeleton article page, Fix error page showing when loading

---

apps/api/app/repositories/topics_repository.py

feat: implement deletion of orphaned keywords with no topic links

---

apps/frontend/app/custom-components/breaking-news/breaking-news-card.tsx

chore: breaking news link new tab

---

apps/api/app/api/v1/endpoints/subscription_controller.py

Fix: get_all_subscriptions only as superuser

---

apps/api/app/services/search_profiles_service.py

fix string

---

apps/frontend/app/custom-components/admin-settings/data-table.tsx
apps/frontend/app/custom-components/profile/edit/data-table-subscriptions.tsx
apps/frontend/app/pages/crawler-stats/crawler-stats.tsx

- fixed cutoff (added padding)
- other tables besides these two were fine

Fix/crawler table (and orga table)

---

apps/api/app/services/email_service.py

Remove coma from email salutation

---

apps/frontend/app/custom-components/dashboard/profile-card.tsx
apps/frontend/app/custom-components/profile/edit/data-table-subscriptions.tsx
apps/frontend/app/pages/admin/dialogs/subscription-dialog.tsx
apps/frontend/app/pages/crawler-stats/crawler-stats.tsx
apps/frontend/app/pages/organisation-settings/organisation-settings-page.tsx
apps/frontend/app/pages/search-profile/search-profile.tsx

- make cards slightly bigger as requested in TL meeting
- make subscriptions sortable and by default sorted by active = true
- dont make subscription dialog jump depending on paywalled
- reduce bottom border on crawler stats & organisation settings (requested in TL meeting)
- change crawler stats badges to flex-row

chore: cleanup frontend issues

---

apps/backend/.env.example
apps/backend/app/core/config.py
apps/backend/app/services/article_cleaner/cleaner_llm.py
apps/backend/app/services/article_summary_service.py
apps/backend/app/services/chatbot_service/chatbot_response.py
apps/backend/app/services/llm_service/llm_client.py
apps/backend/app/services/llm_service/llm_models.py
apps/backend/app/services/login_llm_service.py
apps/backend/app/services/search_profiles_service.py
apps/backend/app/services/translation_service.py
apps/backend/tests/unit_tests/test_llm_service.py

552 refactor centralize llm model configuration management v1

---

apps/frontend/app/custom-components/article/article-body.tsx

Reduce size image, Unround image corners

---

apps/backend/alembic/versions/0c826f19ce87_add_empty_status_to_report.py
apps/backend/app/api/v1/endpoints/article_controller.py
apps/backend/app/models/report.py
apps/backend/app/services/email_service.py
apps/backend/app/services/locales/de/LC_MESSAGES/translations.po
apps/backend/app/services/pdf_service/pdf_service.py
apps/backend/app/services/report_service.py
apps/backend/app/templates/email_template.html

If there are no matches we don't upload the pdf and we set the report status to 'empty' to send a special email:

Fix: empty pdf

---

infra/main.tf
infra/modules/scheduler/main.tf

This pr solves an issue on the scheduler configuration for both `dev` and `prod`.

fix: scheduler

---

apps/backend/app/models/breaking_news.py
apps/backend/app/models/email.py
apps/backend/app/services/email_service.py
apps/backend/app/services/llm_service/prompts/breaking_news_translation_prompt.py
apps/backend/app/services/locales/de/LC_MESSAGES/translations.po
apps/backend/app/services/translation_service.py
apps/backend/app/services/web_harvester/breaking_news_crawler.py
apps/backend/app/templates/breaking_news_template.html

This PR includes:
•	Added prompt for translating breaking news
•	Implemented async def translate_breaking_news_fields() in translation_service
•	Integrated translation logic into fetch_breaking_news_newsapi():
•	For each article, sends emails to users in their preferred language (English or German)
•	Calls the LLM only when necessary
•	Ensured emails are sent in the user’s preferred language by:
•	Updating the Jinja2 email template
•	Adjusting the translations.po file
•	Tested the email output
Ready for review.

606 translate breaking news

---

apps/backend/app/models/breaking_news.py
apps/backend/app/models/email_conversation.py
apps/backend/app/repositories/chatbot_repository.py
apps/backend/app/services/chatbot_service/chatbot_context.py
apps/backend/app/services/chatbot_service/chatbot_response.py
apps/backend/app/services/chatbot_service/chatbot_service.py
apps/backend/app/services/email_service.py

370 chatbot include conversation ids in the email subject after first response to user

---

apps/backend/app/models/breaking_news.py
apps/backend/app/schemas/breaking_news_schemas.py
apps/backend/app/services/email_service.py
apps/backend/app/services/pdf_service/markdown_utils.py
apps/backend/app/services/translation_service.py
apps/backend/app/services/web_harvester/breaking_news_crawler.py

little md parser 
breaking news can be get by frontend

635 make breaking news visible for frontend
